#!/usr/bin/env python3
"""Generate the embedded HVIF toolbar and control icons from the checked-in
Font Awesome SVG artwork (the pipeline of airShot's tools/make-tool-icons.py).

Only regeneration needs fontTools (pip install fonttools); normal Haiku builds
use src/ui/IconData.h directly. Font Awesome Free 6.7.2 artwork is CC BY 4.0.
See resources/icons/README.md for attribution and the icon mapping.

    python3 tools/make-tool-icons.py
"""
from pathlib import Path
import xml.etree.ElementTree as ET

from fontTools.pens.basePen import BasePen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.svgLib.path import parse_path

import hvif

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / 'resources/icons/fontawesome'


class IconPen(BasePen):
    """Convert SVG contours to HVIF points with incoming/outgoing handles."""
    def __init__(self, transform):
        super().__init__(None)
        self.transform = transform
        self.paths = []
        self.points = []

    def _moveTo(self, point):
        point = self.transform(*point)
        self.points = [[point, point, point]]

    def _lineTo(self, point):
        point = self.transform(*point)
        self.points.append([point, point, point])

    def _curveToOne(self, first, second, end):
        first, second, end = [self.transform(*p) for p in (first, second, end)]
        self.points[-1][2] = first
        self.points.append([end, second, end])

    def _closePath(self):
        if self.points[-1][0] == self.points[0][0]:
            self.points[0][1] = self.points.pop()[1]
        self.paths.append({'closed': True, 'points': self.points})
        self.points = []

    def _endPath(self):
        raise ValueError('Icon artwork must use closed, filled contours')


def svg_icon(name, size=48):
    root = ET.parse(SOURCES / ('solid-' + name + '.svg')).getroot()
    data = [p.attrib['d'] for p in root.findall('{http://www.w3.org/2000/svg}path')]
    bounds = BoundsPen(None)
    for path in data:
        parse_path(path, bounds)
    left, top, right, bottom = bounds.bounds
    # Centre on the actual ink; SVG viewBoxes have inconsistent whitespace.
    scale = min(size / (right - left), size / (bottom - top))

    def transform(x, y):
        return (32 + (x - (left + right) / 2) * scale,
                32 + (y - (top + bottom) / 2) * scale)

    pen = IconPen(transform)
    for path in data:
        parse_path(path, pen)
    return {'styles': [{'color': (0, 0, 0, 255)}], 'paths': pen.paths,
            'shapes': [{'style': 0, 'paths': list(range(len(pen.paths)))}]}


# (constant name, Font Awesome icon)
ICONS = [
    ('Open', 'folder-open'),
    ('Save', 'floppy-disk'),
    ('BoardLayout', 'table-columns'),
    ('BcmLayout', 'list-ol'),
    ('CompactLayout', 'compress'),
    ('Reset', 'rotate-left'),
    ('Device', 'microchip'),
    ('ToggleOn', 'toggle-on'),
    ('ToggleOff', 'toggle-off'),
    ('Info', 'circle-info'),
]


def main():
    lines = ['// Generated by tools/make-tool-icons.py; do not edit.',
             '// Font Awesome Free 6.7.2, Copyright 2024 Fonticons, Inc. (CC BY 4.0).',
             '// See resources/icons/README.md and fontawesome/LICENSE.txt.',
             '#pragma once', '', '#include <SupportDefs.h>', '',
             'namespace airpins {', '']
    total = 0
    for name, source in ICONS:
        data = hvif.encode(svg_icon(source))
        hvif.decode(data)
        total += len(data)
        lines.append('static const uint8 k%sIconData[] = {' % name)
        for start in range(0, len(data), 12):
            lines.append('\t' + ', '.join('0x%02x' % b for b in data[start:start + 12]) + ',')
        lines.extend(['};', ''])
    lines.append('enum IconId {')
    for name, _ in ICONS:
        lines.append('\tkIcon%s,' % name)
    lines.extend(['\tkIconCount', '};', ''])
    lines.append('static const struct { const uint8* data; size_t size; } kIconData[] = {')
    for name, _ in ICONS:
        lines.append('\t{ k%sIconData, sizeof(k%sIconData) },' % (name, name))
    lines.extend(['};', '', '}\t// namespace airpins', ''])
    (ROOT / 'src/ui/IconData.h').write_text('\n'.join(lines))
    print('Generated %d icons (%d bytes of HVIF)' % (len(ICONS), total))


if __name__ == '__main__':
    main()
